version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: username/repo:tag
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:[A[A[A[A[A[A[A[A[A[A[A[A[A[A[C[C[3~[3~[3~[3[Cvishwanath7:getstarted2:path2[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[/g[C[C-started2:path2[B[B[B[B[D[D[D[D[D[D[D[B[B[B[B[B[B[D[D[D[D[D[D[D